# A {{{
[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repository = 'AndrewRadev/switch.vim'

[[plugins]]
repository = 'airblade/vim-gitgutter'
# }}}
# B {{{
[[plugins]]
repository = 'basyura/unite-rails'
unite_sources = ['rails']
# }}}
# C {{{
[[plugins]]
repository = 'cohama/lexima.vim'

[[plugins]]
repository = 'chase/vim-ansible-yaml'

# [[plugins]]
# repository = 'cespare/vim-toml'
# filetypes = 'toml'
# }}}
# D {{{
[[plugins]]
repository = 'dannyob/quickfixstatus'
# }}}
# G {{{
[[plugins]]
repository = 'glts/vim-textobj-comment'
# }}}
# H {{{
[[plugins]]
repository = 'haya14busa/incsearch.vim'
# }}}
# I {{{
[[plugins]]
repository = 'itchyny/lightline.vim'
# }}}
# K {{{
[[plugins]]
repository = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repository = 'kana/vim-textobj-fold'

[[plugins]]
repository = 'kana/vim-textobj-line'

[[plugins]]
repository = 'kana/vim-textobj-user'
# }}}
# L {{{
[[plugins]]
repository = 'LeafCage/foldCC.vim'
# }}}
# M {{{
[[plugins]]
repository = 'matchit.zip'

[[plugins]]
repository = 'mattn/webapi-vim'

[[plugins]]
repository = 'mattn/vim-textobj-url'

[[plugins]]
repository = 'mhinz/vim-startify'

[[plugins]]
repository = 'MaxMellon/molokai'

[[plugins]]
repository = 'MaxMEllon/unite-rails-fat'
depends = ['basyura/unite-rails']
# }}}
# O {{{
[[plugins]]
repository = 'osyo-manga/shabadou.vim'

[[plugins]]
repository = 'osyo-manga/vim-watchdogs'

[[plugins]]
repository = 'osyo-manga/unite-filetype'
depends = ['Shougo/unite.vim']

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'
depends = ['Shougo/unite.vim']
# }}}
# R {{{
[[plugins]]
repository = 'rhysd/clever-f.vim'

[[plugins]]
repository = 'rhysd/vim-textobj-ruby'
# }}}
# S {{{
[[plugins]]
repository = 'Shougo/neomru.vim'

[[plugins]]
repository = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repository = 'Shougo/unite-build'
depends = ['Shougo/unite.vim']

[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
insert = 1

# [[plugins]]
# repository = 'Shougo/deoplete.nvim'
# depends = 'Shougo/context_filetype.vim'
# insert = 1
# neovim = 1

# [[plugins]]
# repository = 'Shougo/neosnippet'

# [[plugins]]
# repository = 'Shougo/neosnippet-snippets'

[[plugins]]
repository = 'soramugi/auto-ctags.vim'

[[plugins]]
repository = 'surround.vim'
# }}}
# T {{{
[[plugins]]
repository = 'The-NERD-tree'

[[plugins]]
repository = 'thinca/vim-singleton'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'tpope/vim-rails'

[[plugins]]
repository = 'tyru/caw.vim'
# }}}
# V {{{
[[plugins]]
repository = 'vimtaku/hl_matchit.vim'
# }}}
# Y {{{
[[plugins]]
repository = 'Yggdroot/indentLine'

[[plugins]]
repository = 'yonchu/accelerated-smooth-scroll'
# }}}
